[[server]]
name = "ZouzouNAS2"
[server.config]
address = "https://periphery:8120"
enabled = true
auto_prune = false

##

[[server]]
name = "zouzoulinux"
[server.config]
address = "https://192.168.2.42:8120"
enabled = true
auto_prune = false

##

[[stack]]
name = "arr"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/arr"
environment = """
  # VARIABLE = value
  MOVIES = [[MEDIA_MOVIES_NAS]]
  SERIES = [[MEDIA_SERIES_NAS]]
  DOWNLOADS = [[MEDIA_DOWNLOADS_NAS]]
  MUSIC = [[MEDIA_MUSIC_NAS]]
  EBOOKS = [[MEDIA_EBOOKS_NAS]]
  AUDIOBOOKS = [[MEDIA_AUDIOBOOKS_NAS]]
"""

##

[[stack]]
name = "audiobookshelf"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/audiobookshelf"
environment = """
  # VARIABLE = value
  AUDIOBOOKS = [[MEDIA_AUDIOBOOKS_NAS]]
  EBOOKS = [[MEDIA_EBOOKS_NAS]]
  COMICS = [[MEDIA_COMICS_NAS]]
  PODCASTS = [[MEDIA_PODCASTS_NAS]]
"""

##

[[stack]]
name = "beszel_agent"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/beszel_agent"
environment = """
# VARIABLE = value
BESZEL_KEY = [[BESZEL_KEY_SECRET]]
"""

##

[[stack]]
name = "edge-browser"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/edge"

##

[[stack]]
name = "freshrss"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/freshrss"

##

[[stack]]
name = "grocy"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/grocy"

##

[[stack]]
name = "karakeep"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/karakeep"
environment = """
  # VARIABLE = value
KARAKEEP_NEXTAUTH_SECRET = [[KARAKEEP_NEXTAUTH_SECRET]]
KARAKEEP_MEILI_MASTER_KEY = [[KARAKEEP_MEILI_MASTER_KEY]]
OPENAI_API_KEY = [[OPENAI_API_KEY]]
"""

##

[[stack]]
name = "music_assistant"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/music_assistant"

##

[[stack]]
name = "template"
template = true
[stack.config]
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/"

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "ZouzouNAS2"

##

[[resource_sync]]
name = "komodo-forge"
[resource_sync.config]
repo = "NiphraDil/komodo-forge"
git_account = "NiphraDil"
resource_path = ["komodo.toml"]
managed = true
delete = true