[[server]]
name = "ZouzouNAS2"
[server.config]
address = "https://192.168.2.117:8120"
enabled = true
auto_prune = false

##

[[server]]
name = "zouzoulinux"
[server.config]
address = "https://192.168.2.42:8120"
enabled = true
auto_prune = false

##

[[stack]]
name = "actual_budget"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/actual"

##

[[stack]]
name = "adguard"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/adguard"

##

[[stack]]
name = "arr"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/arr"
environment = """
  # VARIABLE = value
  MOVIES = [[MEDIA_MOVIES_NAS]]
  SERIES = [[MEDIA_SERIES_NAS]]
  DOWNLOADS = [[MEDIA_DOWNLOADS_NAS]]
  MUSIC = [[MEDIA_MUSIC_NAS]]
  EBOOKS = [[MEDIA_EBOOKS_NAS]]
  AUDIOBOOKS = [[MEDIA_AUDIOBOOKS_NAS]]
"""

##

[[stack]]
name = "audiobookshelf"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/audiobookshelf"
environment = """
  # VARIABLE = value
  AUDIOBOOKS = [[MEDIA_AUDIOBOOKS_NAS]]
  EBOOKS = [[MEDIA_EBOOKS_NAS]]
  COMICS = [[MEDIA_COMICS_NAS]]
  PODCASTS = [[MEDIA_PODCASTS_NAS]]
"""

##

[[stack]]
name = "beszel"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/beszel_main"
environment = """
  # VARIABLE = value
BESZEL_KEY = [[BESZEL_KEY_SECRET]]
"""

##

[[stack]]
name = "beszel_agent"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/beszel_agent"
environment = """
# VARIABLE = value
BESZEL_KEY = [[BESZEL_KEY_SECRET]]
"""

##

[[stack]]
name = "brave"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/brave"
environment = """
  # VARIABLE = value
BRAVE_USER = [[BRAVE_USER]]
BRAVE_PASSWORD = [[BRAVE_PASSWORD]]
"""

##

[[stack]]
name = "cloudflare_ddns"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/cloudflare_ddns"
environment = """
  # VARIABLE = value
CLOUDFLARE_API_TOKEN = [[CLOUDFLARE_API_TOKEN]]
"""

##

[[stack]]
name = "copyparty"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/copyparty"

##

[[stack]]
name = "dawarich"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/dawarich"
environment = """
  # VARIABLE = value
RAILS_ENV = development
MIN_MINUTES_SPENT_IN_CITY = 60
APPLICATION_HOST = 127.0.0.1:32568
TIME_ZONE = Europe/Amsterdam
BACKGROUND_PROCESSING_CONCURRENCY = 10
MAP_CENTER = [52.083416, 4.355778]
DATABASE_HOST = dawarich_db
DATABASE_USERNAME = postgres
DATABASE_PASSWORD = Farwenyadawarich13!
DATABASE_NAME = dawarich
REDIS_URL = redis://dawarich_redis:6379/0
APPLICATION_HOSTS = localhost,gps.zouzounet.nl
SECRET_KEY_BASE = [[DAWARICH_SECRET]]
"""

##

[[stack]]
name = "deemix"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/deemix"

##

[[stack]]
name = "docmost"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/docmost"
environment = """
  # VARIABLE = value
APP_SECRET = [[DOCMOST_APP_SECRET]]
SMTP_USER = [[DOCMOST_SMTP_USER]]
SMTP_PASSWORD = [[DOCMOST_SMTP_PASSWORD]]
"""

##

[[stack]]
name = "duplicati"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/duplicati"
environment = """
  # VARIABLE = value
DUPLICATI_ENCRYPTION_KEY = [[DUPLICATI_ENCRYPTION_KEY]]
"""

##

[[stack]]
name = "edge-browser"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/edge"

##

[[stack]]
name = "freshrss"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/freshrss"

##

[[stack]]
name = "grocy"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/grocy"

##

[[stack]]
name = "guacamole"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/guacamole"

##

[[stack]]
name = "homarr"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/homarr"
environment = """
  # VARIABLE = value
HOMARR_SECRET = [[HOMARR_SECRET_ENCRYPTION_KEY]]
"""

##

[[stack]]
name = "homeassistant"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/home_assistant"

##

[[stack]]
name = "immich"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/immich"
environment = """
  # VARIABLE = value
NODE_ENV = production
TZ = Europe/Amsterdam
DB_HOSTNAME = immich-db
DB_USERNAME = immichuser
DB_PASSWORD = immichpw
DB_DATABASE_NAME = immich
REDIS_HOSTNAME = immich-redis
LOG_LEVEL = log
JWT_SECRET = xia7jNMRT50PgcShC0BTuFxTLPamoYnQO8OKH8jUff4iD0AdtbC8HTZp/Rv4LSdpV7kXbYTvxNrw24NzJJiag2nisYbUmEV8XbJEEboag98z+6KR5djhPPC4/oztoSJHOB2rpPXjv4VNwCAT0PvTKUo3gSY8rDja85DGugYqJ0c=
DISABLE_REVERSE_GEOCODING = false
REVERSE_GEOCODING_PRECISION = 3
PUBLIC_LOGIN_PAGE_MESSAGE = "Welcome to ZouzouPhotos"
IMMICH_WEB_URL = http://immich-web:3000
IMMICH_SERVER_URL = http://immich-server:3001
IMMICH_MACHINE_LEARNING_URL = http://immich-machine-learning:3003
DB_DATA_LOCATION = /volume1/Workshop/docker/immich/db
POSTGRES_INITDB_ARGS = '--data-checksums'
"""

##

[[stack]]
name = "ittools"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/ittools"

##

[[stack]]
name = "jellyfin"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/jellyfin"
environment = """
  # VARIABLE = value
MOVIES = [[MEDIA_MOVIES_LINUX]]
SERIES = [[MEDIA_SERIES_LINUX]]
MUSIC = [[MEDIA_MUSIC_LINUX]]
"""

##

[[stack]]
name = "jellyseerr"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/jellyseerr"

##

[[stack]]
name = "karakeep"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/karakeep"
environment = """
  # VARIABLE = value
KARAKEEP_NEXTAUTH_SECRET = [[KARAKEEP_NEXTAUTH_SECRET]]
KARAKEEP_MEILI_MASTER_KEY = [[KARAKEEP_MEILI_MASTER_KEY]]
OPENAI_API_KEY = [[OPENAI_API_KEY]]
"""

##

[[stack]]
name = "komodo"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/komodo_core"
additional_env_files = ["./compose.env"]

##

[[stack]]
name = "komodo-forge-template"
template = true
[stack.config]
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/"

##

[[stack]]
name = "music_assistant"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/music_assistant"

##

[[stack]]
name = "navidrome"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/navidrome"
environment = """
  # VARIABLE = value
SPOTIFY_ID = [[SPOTIFY_ID]]
SPOTIFY_SECRET = [[SPOTIFY_SECRET]]
LASTFM_API_KEY = [[LASTFM_API_KEY]]
LASTFM_SECRET = [[LASTFM_API_SECRET]]
"""

##

[[stack]]
name = "ollama"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/ollama"
environment = """
  # VARIABLE = value
OLLAMA_WEBUI_SECRET = [[OLLAMA_WEBUI_SECRET]]
"""

##

[[stack]]
name = "portall"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/portall"
environment = """
  # VARIABLE = value
PORTALL_SECRET_KEY = [[PORTALL_SECRET_KEY]]
"""

##

[[stack]]
name = "qbittorrent"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/qbittorrent"
environment = """
  # VARIABLE = value
MOVIES = [[MEDIA_MOVIES_NAS]]
DOWNLOADS = [[MEDIA_DOWNLOADS_NAS]]
SERIES = [[MEDIA_SERIES_NAS]]
MUSIC = [[MEDIA_MUSIC_NAS]]
"""

##

[[stack]]
name = "reitti"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/reitti"
environment = """
  # VARIABLE = value
REITTI_USER = [[REITTI_USER]]
REITTI_PASSWORD = [[REITTI_PASSWORD]]
"""

##

[[stack]]
name = "sabnzbd"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/sabnzbd"

##

[[stack]]
name = "stirlingpdf"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/stirlingpdf"
environment = """
  # VARIABLE = value
INITIAL_USER = [[STIRLING_INITIAL_USER]]
INITIAL_PASSWORD = [[STIRLING_INITIAL_PASSWORD]]
"""

##

[[stack]]
name = "thunderbird"
[stack.config]
server = "zouzoulinux"
auto_pull = false
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/thunderbird"

##

[[stack]]
name = "trip"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/trip"

##

[[stack]]
name = "wyoming"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/wyoming"

##

[[procedure]]
name = "Global Auto Update"
description = "Pulls and auto updates Stacks and Deployments using 'poll_for_updates' or 'auto_update'."
tags = ["system"]
config.schedule = "Every day at 03:00"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "GlobalAutoUpdate", execution.params = {}, enabled = true }
]

##

[[procedure]]
name = "restart on plan"

[[procedure.config.stage]]
name = "Stage 1"
enabled = false
executions = [
  { execution.type = "RestartStack", execution.params.stack = "freshrss", execution.params.services = [], enabled = true }
]

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "ZouzouNAS2"

##

[[resource_sync]]
name = "komodo-forge"
[resource_sync.config]
repo = "NiphraDil/komodo-forge"
git_account = "NiphraDil"
resource_path = ["komodo.toml"]
managed = true
delete = true