[[server]]
name = "ZouzouNAS2"
[server.config]
address = "https://periphery:8120"
enabled = true
auto_prune = false

##

[[server]]
name = "zouzoulinux"
[server.config]
address = "https://192.168.2.42:8120"
enabled = true
auto_prune = false

##

[[stack]]
name = "adguard"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/adguard"

##

[[stack]]
name = "arr"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/arr"
environment = """
  # VARIABLE = value
  MOVIES = [[MEDIA_MOVIES_NAS]]
  SERIES = [[MEDIA_SERIES_NAS]]
  DOWNLOADS = [[MEDIA_DOWNLOADS_NAS]]
  MUSIC = [[MEDIA_MUSIC_NAS]]
  EBOOKS = [[MEDIA_EBOOKS_NAS]]
  AUDIOBOOKS = [[MEDIA_AUDIOBOOKS_NAS]]
"""

##

[[stack]]
name = "audiobookshelf"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/audiobookshelf"
environment = """
  # VARIABLE = value
  AUDIOBOOKS = [[MEDIA_AUDIOBOOKS_NAS]]
  EBOOKS = [[MEDIA_EBOOKS_NAS]]
  COMICS = [[MEDIA_COMICS_NAS]]
  PODCASTS = [[MEDIA_PODCASTS_NAS]]
"""

##

[[stack]]
name = "beszel"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/beszel_main"
environment = """
  # VARIABLE = value
BESZEL_KEY = [[BESZEL_KEY_SECRET]]
"""

##

[[stack]]
name = "beszel_agent"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/beszel_agent"
environment = """
# VARIABLE = value
BESZEL_KEY = [[BESZEL_KEY_SECRET]]
"""

##

[[stack]]
name = "dawarich"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/dawarich"
environment = """
  # VARIABLE = value
RAILS_ENV = development
MIN_MINUTES_SPENT_IN_CITY = 60
APPLICATION_HOST = 127.0.0.1:32568
TIME_ZONE = Europe/Amsterdam
BACKGROUND_PROCESSING_CONCURRENCY = 10
MAP_CENTER = [52.083416, 4.355778]
DATABASE_HOST = dawarich_db
DATABASE_USERNAME = postgres
DATABASE_PASSWORD = Farwenyadawarich13!
DATABASE_NAME = dawarich
REDIS_URL = redis://dawarich_redis:6379/0
APPLICATION_HOSTS = localhost,gps.zouzounet.nl
SECRET_KEY_BASE = [[DAWARICH_SECRET]]
"""

##

[[stack]]
name = "docmost"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/docmost"
environment = """
  # VARIABLE = value
APP_SECRET = [[DOCMOST_APP_SECRET]]
SMTP_USER = [[DOCMOST_SMTP_USER]]
SMTP_PASSWORD = [[DOCMOST_SMTP_PASSWORD]]
"""

##

[[stack]]
name = "edge-browser"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/edge"

##

[[stack]]
name = "freshrss"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/freshrss"

##

[[stack]]
name = "grocy"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/grocy"

##

[[stack]]
name = "guacamole"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/guacamole"

##

[[stack]]
name = "homarr"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/homarr"
environment = """
  # VARIABLE = value
HOMARR_SECRET = [[HOMARR_SECRET_ENCRYPTION_KEY]]
"""

##

[[stack]]
name = "homeassistant"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/home_assistant"

##

[[stack]]
name = "ittools"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/ittools"

##

[[stack]]
name = "jellyfin"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/jellyfin"
environment = """
  # VARIABLE = value
MOVIES = [[MEDIA_MOVIES_LINUX]]
SERIES = [[MEDIA_SERIES_LINUX]]
MUSIC = [[MEDIA_MUSIC_LINUX]]
"""

##

[[stack]]
name = "jellyseerr"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/jellyseerr"

##

[[stack]]
name = "karakeep"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/karakeep"
environment = """
  # VARIABLE = value
KARAKEEP_NEXTAUTH_SECRET = [[KARAKEEP_NEXTAUTH_SECRET]]
KARAKEEP_MEILI_MASTER_KEY = [[KARAKEEP_MEILI_MASTER_KEY]]
OPENAI_API_KEY = [[OPENAI_API_KEY]]
"""

##

[[stack]]
name = "komodo-forge-template"
template = true
[stack.config]
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/"

##

[[stack]]
name = "music_assistant"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/music_assistant"

##

[[stack]]
name = "navidrome"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/navidrome"
environment = """
  # VARIABLE = value
SPOTIFY_ID = [[SPOTIFY_ID]]
SPOTIFY_SECRET = [[SPOTIFY_SECRET]]
LASTFM_API_KEY = [[LASTFM_API_KEY]]
LASTFM_SECRET = [[LASTFM_API_SECRET]]
"""

##

[[stack]]
name = "ollama"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/ollama"
environment = """
  # VARIABLE = value
OLLAMA_WEBUI_SECRET = [[OLLAMA_WEBUI_SECRET]]
"""

##

[[stack]]
name = "portall"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/portall"
environment = """
  # VARIABLE = value
PORTALL_SECRET_KEY = [[PORTALL_SECRET_KEY]]
"""

##

[[stack]]
name = "qbittorrent"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/qbittorrent"
environment = """
  # VARIABLE = value
MOVIES = [[MEDIA_MOVIES_NAS]]
DOWNLOADS = [[MEDIA_DOWNLOADS_NAS]]
SERIES = [[MEDIA_SERIES_NAS]]
MUSIC = [[MEDIA_MUSIC_NAS]]
"""

##

[[stack]]
name = "sabnzbd"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/sabnzbd"

##

[[stack]]
name = "stirlingpdf"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/stirlingpdf"
environment = """
  # VARIABLE = value
INITIAL_USER = [[STIRLING_INITIAL_USER]]
INITIAL_PASSWORD = [[STIRLING_INITIAL_PASSWORD]]
"""

##

[[stack]]
name = "wyoming"
[stack.config]
server = "zouzoulinux"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/wyoming"

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "ZouzouNAS2"

##

[[resource_sync]]
name = "komodo-forge"
[resource_sync.config]
repo = "NiphraDil/komodo-forge"
git_account = "NiphraDil"
resource_path = ["komodo.toml"]
managed = true
delete = true