[[server]]
name = "ZouzouNAS2"
[server.config]
address = "https://periphery:8120"
enabled = true
auto_prune = false

##

[[server]]
name = "zouzoulinux"
[server.config]
address = "https://192.168.2.42:8120"
enabled = true
auto_prune = false

##

[[stack]]
name = "edge-browser"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/edge"

##

[[stack]]
name = "freshrss"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/freshrss"

##

[[stack]]
name = "grocy"
[stack.config]
server = "ZouzouNAS2"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/grocy"

##

[[stack]]
name = "template"
template = true
[stack.config]
git_account = "NiphraDil"
repo = "NiphraDil/komodo-forge"
run_directory = "stacks/"

##

[[builder]]
name = "local"
[builder.config]
type = "Server"
params.server_id = "ZouzouNAS2"

##

[[resource_sync]]
name = "komodo-forge"
[resource_sync.config]
repo = "NiphraDil/komodo-forge"
git_account = "NiphraDil"
resource_path = ["komodo.toml"]
managed = true
delete = true