services:
  degoog:
    image: ghcr.io/degoog-org/degoog:latest
    volumes:
      - /var/lib/degoog:/app/data
    ports:
      - "4444:4444"
      - "3031:3031"
    environment:
      DEGOOG_SETTINGS_PASSWORDS: ${DEGOOG_PASSWORD}  
    restart: unless-stopped