services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8081:80'
      - '81:81'
      - '4444:443'
    volumes:
      - /volume1/Workshop/docker/npm/data:/data
      - /volume1/Workshop/docker/npm/letsencrypt:/etc/letsencrypt