version: "3.9"
services:
  web:
    image: ghcr.io/karakeep-app/karakeep:release
    container_name: Karakeep-WEB
    restart: on-failure:5
    volumes:
      - /volume1/Workshop/docker/hoarder/data:/data:rw
    ports:
      - 3022:3000
    environment:
      REDIS_HOST: redis
      MEILI_ADDR: http://meilisearch:7700
      DATA_DIR: /data
      NEXTAUTH_SECRET: ${KARAKEEP_NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${KARAKEEP_MEILI_MASTER_KEY}
      BROWSER_WEB_URL: http://chrome:9222
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:100
    container_name: Karakeep-CHROME
    restart: on-failure:5
    command:
      - --no-sandbox
      - --disable-gpu
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      
  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: Karakeep-MEILI
    restart: unless-stopped
    volumes:
      - /volume1/Workshop/docker/hoarder/meili:/meili_data:rw
    environment:
     MEILI_MASTER_KEY: ${KARAKEEP_MEILI_MASTER_KEY}
     MEILI_NO_ANALYTICS: true